[package]
name = "dev-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
ignore = "0.4.22"
serde_json = "1.0.115"

[[bin]]
name = "fafnir"
path = "src/main.rs"